# Generated by Django 6.0.5 on 2026-05-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Price in INR (paise-free)')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True)),
                ('emoji', models.CharField(default='🛍️', max_length=10)),
                ('badge', models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New'), ('', 'None')], default='', max_length=10)),
                ('rating', models.PositiveSmallIntegerField(default=4)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
        ),
    ]
