const r = require('express').Router();
const { authenticate, optionalAuth } = require('../middleware/auth');
const upload = require('../middleware/upload');
const c = require('../controllers/userController');
r.get('/suggestions', optionalAuth, c.getSuggestions);
r.get('/', optionalAuth, c.listUsers);
r.get('/:id', optionalAuth, c.getUser);
r.put('/:id', authenticate, upload.fields([{name:'profile_image',maxCount:1},{name:'cover_image',maxCount:1}]), c.updateUser);
r.post('/:id/follow', authenticate, c.followUser);
r.delete('/:id/unfollow', authenticate, c.unfollowUser);
r.get('/:id/followers', c.getFollowers);
r.get('/:id/following', c.getFollowing);
module.exports = r;
